**test back reflection geometry calculation of angles and X, Y positions**

In [4]:
import LaueTools as LT
import numpy as np

In [5]:
LT

<module 'LaueTools' from '/home/micha/lauetoolsgithub/LaueTools/__init__.py'>

In [6]:
import LaueTools.LaueGeometry as LTGeo

-- OK! You are using python 3


In [4]:
LTGeo.calc_uflab_back

<function LaueTools.LaueGeometry.calc_uflab_back(xcam, ycam, calib, returnAngles=1, verbose=0, pixelsize=0.08056640625, rectpix=0)>

In [ ]:
LTGeo.calc_xycam_backreflection

In [7]:
calib = [1000,1000,1000,0,0]
xycam=np.array([[1000,1000+50],
                [1000,1000-50],
                [1000-50,1000]])
pixelsize = 1
xcam, ycam=xycam.T
print('xcam',xcam)
tth_chi=LTGeo.calc_uflab_back(xcam, ycam, calib,returnAngles=True, pixelsize=pixelsize, verbose=1)
uflab_IM = LTGeo.calc_uflab_back(xcam, ycam, calib,returnAngles=False, pixelsize=pixelsize)

xcam [1000 1000  950]
Back reflection GEOMETRY
[ 0.000000000000000e+00 -1.000000000000000e+00  6.123233995736766e-17]
xOM, yOM, zOM [  0.   0. -50.] [ 3.061616997868383e-15 -3.061616997868383e-15  0.000000000000000e+00] [ 50. -50.   0.]
xca0, yca0 [  0.   0. -50.] [ 50. -50.   0.]
IMlab [[    0. -1000.    50.]
 [    0. -1000.   -50.]
 [  -50. -1000.     0.]]
nIMlab [1001.2492197250393 1001.2492197250393 1001.2492197250393]
uflab [[ 0.      -0.99875  0.04994]
 [ 0.      -0.99875 -0.04994]
 [-0.04994 -0.99875  0.     ]]
chi_JSM [  -0.               -180.                 89.99999999999993]
2theta [177.13759477388822 177.13759477388822 177.13759477388822]
Back reflection GEOMETRY


In [5]:
1000/1001

0.999000999000999

In [8]:
tth_chi, uflab_IM

((array([90.11459140623779 , 90.05124688946022 , 26.565051177078004]),
  array([-180.              ,  116.56505117707799, -180.              ])),
 (array([[ 0.000000000000000e+00, -1.999996000012122e-03,
          -9.999980000059999e-01],
         [-8.944268332292542e-01, -8.944268332293089e-04,
          -4.472134166146271e-01],
         [ 0.000000000000000e+00,  8.944271909999157e-01,
          -4.472135954999580e-01]]),
  array([[   0.               ,   -0.100000000000006,  -50.               ],
         [-100.               ,   -0.100000000000006,  -50.               ],
         [   0.               ,  100.               ,  -50.000000000000014]])))

In [6]:
_xcam, _ycam, th0 =  LTGeo.calc_xycam_backreflection(uflab_IM[0],calib, pixelsize=pixelsize,)
_xycam = np.array([xcam, ycam]).T
_xycam, 2*th0

/home/micha/lauetoolsgithub/LaueTools/LaueGeometry.py:808: RuntimeWarning: divide by zero encountered in true_divide
  Energy_2 = CST_CONV_LAMBDA_KEV * norme_qflab2 ** 2 / (2.0 * np.sin(th0_2 * DEG))


(array([[1000, 1000],
        [   0, 1000],
        [1000,    0]]),
 array([ 0.              , 63.43494882292201, 63.43494882292201]))